# binary search program makefile
#Talifhani Nemaangani
#15 April 2023


JAVAC=/usr/bin/javac
.SUFFIXES: .java .class

SRCDIR=src
BINDIR=bin

$(BINDIR)/%.class:$(SRCDIR)/%.java
	$(JAVAC) -d $(BINDIR)/ -cp $(BINDIR) $<

CLASSES=BinaryTreeNode.class \
         BTQueueNode.class BTQueue.class BinaryTree.class \
         BinarySearchTree.class BinarySearchTreeTest.class \
		 Post.class Account.class TokTik.class

CLASS_FILES=$(CLASSES:%.class=$(BINDIR)/%.class)

default: $(CLASS_FILES)




clean:
	rm $(BINDIR)/*.class 

run: $(CLASS_FILE)
	 java -cp bin TokTik
 

	
